from datasets import load_dataset

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer

dataset = load_dataset('mrochk/src_cfg_ast')

def f(row):
    row['ast'] = row['ast'].replace(' ', '_')
    return row

train = dataset['train'].map(f)

tokenizer = Tokenizer(BPE(unk_token="[UNK]"))

from tokenizers.pre_tokenizers import Split, Whitespace

pretokenizer = Whitespace()

tokenizer.pre_tokenizer = pretokenizer

for vocab_size in [500, 1000, 2000, 5000]:

    trainer = BpeTrainer(
        vocab_size=vocab_size, 
        special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"]
    )

    tokenizer.train_from_iterator(train['ast'], trainer, len(train['ast']))

    tokenizer.save(f'tokenizer_ast_{vocab_size}.json')

inp = """
MODULE FUNCTIONDEF ARGUMENTS ARG ARG ARG ARG CONSTANT EXPR CONSTANT EXPR CALL ATTRIBUTE NAME LOAD LOAD ASSIGN NAME STORE LIST LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD CONSTANT NAME LOAD ASSIGN NAME STORE NAME LOAD IF BOOLOP OR COMPARE NAME LOAD IS CONSTANT UNARYOP NOT NAME LOAD RAISE CALL NAME LOAD CONSTANT CONSTANT FOR TUPLE NAME STORE NAME STORE STORE CALL NAME LOAD NAME LOAD WHILE COMPARE CALL NAME LOAD NAME LOAD GTE NAME LOAD ASSIGN NAME STORE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD NAME LOAD ASSIGN NAME STORE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD NAME LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD CONSTANT IF COMPARE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD EQ ATTRIBUTE NAME LOAD LOAD RETURN EXPR CALL ATTRIBUTE NAME LOAD LOAD CONSTANT SUBSCRIPT NAME LOAD CONSTANT LOAD SUBSCRIPT NAME LOAD CONSTANT LOAD ASSIGN NAME STORE CALL ATTRIBUTE NAME LOAD LOAD KEYWORD ATTRIBUTE NAME LOAD LOAD KEYWORD TUPLE NAME LOAD SUBSCRIPT NAME LOAD CONSTANT LOAD LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD TUPLE NAME LOAD SUBSCRIPT NAME LOAD CONSTANT LOAD LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD ATTRIBUTE NAME LOAD LOAD WHILE NAME LOAD ASSIGN NAME STORE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD NAME LOAD IF NAME LOAD ASSIGN NAME STORE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD NAME LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD CONSTANT IF COMPARE CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD NOTEQ ATTRIBUTE NAME LOAD LOAD EXPR CALL ATTRIBUTE NAME LOAD LOAD NAME LOAD
""".replace(' ', '_')

print(inp)

print(tokenizer.encode(inp).tokens)
